### ISSUE TITLE
Bridge collapse 

### ISSUE THREAD

**Issue by phenix13** [werthdavid/homebridge-weather#7] opened 2017-10-03 00:32 UTC
Breaking the internet due the bridge to collapse, sometimes there are no networks at home,but wifi is still well, lots of equipment work well,but when need to update temperature date,the bridge will collapse.

**Comment by werthdavid** [comment] 2017-10-11 15:47
Will check on that

**Comment by werthdavid** [comment] 2017-10-11 16:10
Can't reproduce that issue, can you provide a log-output of homebridge?

**Comment by werthdavid** [comment] 2018-01-19 10:22
Will close the issue

**Closed as completed by werthdavid** 2018-01-19 10:22 UTC
Labels: bug
