### ISSUE TITLE
Log in eve APP

### ISSUE THREAD

**Issue by sotoje** [werthdavid/homebridge-weather#26] opened 2019-11-26 01:15 UTC
Hi
The historical data is not saved since one day ago.

I have defined polling and enable history vars.

I split temp and humidity in two sensors like this
60
        },
        {
            "accessory": "Weather",
            "apikey": "xxxxxxxx",
            "location": "Xxxxxc",
            "name": "Temperatura Exterior",
            "showHumidity": false,
            "pollingInterval": 10,
            "enableHistory": true
        },
        {
            "accessory": "Weather",
            "apikey": "xxxxxxxx",
            "location": "xxxxxxxc",
            "name": "Humedad Exterior",
            "showTemperature": false,
            "pollingInterval": 10,
            "enableHistory": true
        },

**Comment by werthdavid** [comment] 2019-12-18 06:31
Duplicate of #22

**Closed as completed by werthdavid** 2019-12-18 06:31 UTC
Labels: duplicate
