### ISSUE TITLE
Warning: 'This plugin slows down Homebridge' in log

### ISSUE THREAD

**Issue by dVIAN13** [werthdavid/homebridge-weather#37] opened 2021-02-22 06:10 UTC
Hello,

After upgrading to Homebridge 1.3.0, I recently discovered the following in my log files.

`[2/21/2021, 10:04:17 PM] [homebridge-weather] This plugin slows down Homebridge. The read handler for the characteristic 'Current Temperature' was slow to respond! See https://git.io/JtMGR for more info.
[2/21/2021, 10:04:17 PM] [homebridge-weather] This plugin slows down Homebridge. The read handler for the characteristic 'Current Relative Humidity' was slow to respond! See https://git.io/JtMGR for more info.`

Is there anything I can do to ensure this does not affect anything?

**Comment by werthdavid** [comment] 2021-02-22 09:49
Oh wow, that's new. I have to adjust the code accordingly

**Comment by werthdavid** [comment] 2021-02-22 12:23
Hmm I'm not sure if I can fix that at all.
The problem is that homebridge, when it triggers a plugin to deliver data, expects those values "fast". homebridge-weather needs to call OpenWeatherMap-API first which is of course slow as it has to go over the internet.
As suggested, the plugin could send back e.g. "0 degrees" and as soon as the network-request is finished the correct value will be visible. Problem is that for a short time it would display 0 and in case an error occurs it would always show 0 and the plugin wouldn't report a problem. I will therefore mark it as "won't fix" until the design can be changed with error handling or I come up with another idea (maybe another plugin has fixed that issue already).

**Comment by martinnock** [comment] 2021-02-22 12:45
You may look at homebridge-weather-plus - I am not good at reading the code, but from a usability point of view, the plugin populates 0 initially, then updates with values once received.

**Comment by werthdavid** [comment] 2021-02-22 12:50
Good point, I did write the code for openweathermap in that plugin as well. Let's see how the error handling takes place there..

**Comment by werthdavid** [comment] 2021-02-22 12:54
Okay well it just always shows 0... I don't like that too much as the error is "hidden" but maybe it's still better than always getting that message

**Comment by dVIAN13** [comment] 2021-02-22 17:55
FWIW, after the latest update today, the warning message no longer presents itself after HB startup. 👍

**Comment by bondskin** [comment] 2021-02-27 16:06
still existing here:
[27/02/2021, 17:00:10] [homebridge-weather] This plugin slows down Homebridge. The read handler for the characteristic 'Current Relative Humidity' was slow to respond! See https://git.io/JtMGR for more info.

**Closed as completed** 2022-07-11 08:27 UTC
Labels: wontfix
